config/routes.rb
Rails.application.routes.draw do

  # Root path
  root to: 'pages#home'


post '/users/:id' => 'users#show'
  # Create routes for users to create accounts, login and view/edit/delete their profile
  # users     GET    /users(.:format)          users#index
  #           POST   /users(.:format)          users#create
  # new_user  GET    /users/new(.:format)      users#new
  # edit_user GET    /users/:id/edit(.:format) users#edit
  # user      GET    /users/:id(.:format)      users#show
  #           PATCH  /users/:id(.:format)      users#update
  #           PUT    /users/:id(.:format)      users#update
  #           DELETE /users/:id(.:format)      users#destroy
  resources :users

  # Login/logout routes
  get '/login'  => 'session#new'        # showing the login form
  post '/login' => 'session#create'     # form submits to here, performs login, redirects
  delete '/login' => 'session#destroy'  # logout link goes here, perform logout, redirect

  # Create routes for puzzles - DO WE NEED ALL OF THESE ROUTES?
  #   puzzles GET    /puzzles(.:format)          puzzles#index
  #   POST   /puzzles(.:format)          puzzles#create
  # new_puzzle GET    /puzzles/new(.:format)      puzzles#new
  # edit_puzzle GET    /puzzles/:id/edit(.:format) puzzles#edit
  # puzzle GET    /puzzles/:id(.:format)      puzzles#show
  #   PATCH  /puzzles/:id(.:format)      puzzles#update
  #   PUT    /puzzles/:id(.:format)      puzzles#update
  #   DELETE /puzzles/:id(.:format)      puzzles#destroy
  resources :puzzles

  # Create routes for games - DO WE NEED ALL OF THESE ROUTES?
  #   games   GET    /games(.:format)            games#index
  #           POST   /games(.:format)            games#create
  # new_game  GET    /games/new(.:format)        games#new
  # edit_game GET    /games/:id/edit(.:format)   games#edit
  # game      GET    /games/:id(.:format)        games#show
  #           PATCH  /games/:id(.:format)        games#update
  #           PUT    /games/:id(.:format)        games#update
  #           DELETE /games/:id(.:format)        games#destroy
  resources :games

    #  Create route for end of game
    get 'games/:id/gameover' => 'games#gameover'

end

app/models/user.rb
class User < ApplicationRecord

    # Use the bcrypt gem to encrypt passwords when user creates account, and store only the encrypted version in the 'users' table
    has_secure_password

    # Ensure user enters valid & unique email address
    validates :email,
            presence: true,
            uniqueness: {case_sensitive: false},
            length: {minimum: 4, maximum: 254},
            format: {with: /\A(.+)@(.+)\z/, message: "Please check the email address. It's invalid."}

    # Ensure username is atleast 2 chars long
    validates :username, length: { minimum: 2 }

    # Relationships
    has_many :games
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # CREATE
    def new
      @user = User.new
    end # new

    def create
      # Create user object
      @user = User.create user_params

      # Confirm data was saved to the database
      if @user.persisted?

        # Log user in once account created
        session[:user_id] = @user.id

        # Direct user to home
        redirect_to root_path

      else
      # Account creation failed
        # Re-render form
        render :new
      end # if
    end # create

    # READ
    def index
    end # index

    def show
      @games = Game.where(user_id: params[:id])
    end # show

    # UPDATE
    def edit
    end # edit

    def update
    end # update

    # DELETE
    def destroy
    end # destroy

    private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :username)
    end # user_params
  end # UsersController

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>
<%# TODO: EDIT PROFILE PAGE %>

app/views/users/new.html.erb
<article>
  <section>
    <header>
      <h1 class="page-title">Welcome to Tech Job Corp.!</h1>
      <p>We're so happy you've decided to apply. Submit your resume below and we'll get back to you shortly (...probably just ghost you).</p>
    </header>
  </section>


<% if @user.errors.full_messages.any? %>
  <strong>Errors:</strong>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
    <% end  %>
  </ul>
<% end %>

<%# TODO: Move form to partial %>
<%# Create account form %>
<%= form_with model: @user, local: true do |f| %>
  <%= f.label :username, 'Applicant name' %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "Let's play", :class => 'button-primary' %>
  <%= link_to 'Cancel', root_path, :class => 'button button-secondary' %>
<% end %> 
</article>

app/views/users/show.html.erb
<h1>Welcome <%= @current_user.username%></h1>

<p>Your Score History</p>
<ul>
  <% @games.each do |g| %>
  <li>ID: <%= g.id%></li>

  <li>Currently in progress:<%= g.in_progress%></li>
  <li>Time Game Started: <%= g.created_at%></li>
  <li>Last played: <%= g.updated_at%></li>
  <li>Total Game Time: <%= g.game_time%></li>
  <li>Score: <%= g.score%></li>
  <br>
  <%end%>
</ul>

<%= link_to "Return to Home Page", new_game_path %>