config/routes.rb
Rails.application.routes.draw do

  # Root path
  root to: 'pages#home'


post '/users/:id' => 'users#show'
  # Create routes for users to create accounts, login and view/edit/delete their profile
  # users     GET    /users(.:format)          users#index
  #           POST   /users(.:format)          users#create
  # new_user  GET    /users/new(.:format)      users#new
  # edit_user GET    /users/:id/edit(.:format) users#edit
  # user      GET    /users/:id(.:format)      users#show
  #           PATCH  /users/:id(.:format)      users#update
  #           PUT    /users/:id(.:format)      users#update
  #           DELETE /users/:id(.:format)      users#destroy
  resources :users

  # Login/logout routes
  get '/login'  => 'session#new'        # showing the login form
  post '/login' => 'session#create'     # form submits to here, performs login, redirects
  delete '/login' => 'session#destroy'  # logout link goes here, perform logout, redirect

  # Create routes for puzzles - DO WE NEED ALL OF THESE ROUTES?
  #   puzzles GET    /puzzles(.:format)          puzzles#index
  #   POST   /puzzles(.:format)          puzzles#create
  # new_puzzle GET    /puzzles/new(.:format)      puzzles#new
  # edit_puzzle GET    /puzzles/:id/edit(.:format) puzzles#edit
  # puzzle GET    /puzzles/:id(.:format)      puzzles#show
  #   PATCH  /puzzles/:id(.:format)      puzzles#update
  #   PUT    /puzzles/:id(.:format)      puzzles#update
  #   DELETE /puzzles/:id(.:format)      puzzles#destroy
  resources :puzzles

  # Create routes for games - DO WE NEED ALL OF THESE ROUTES?
  #   games   GET    /games(.:format)            games#index
  #           POST   /games(.:format)            games#create
  # new_game  GET    /games/new(.:format)        games#new
  # edit_game GET    /games/:id/edit(.:format)   games#edit
  # game      GET    /games/:id(.:format)        games#show
  #           PATCH  /games/:id(.:format)        games#update
  #           PUT    /games/:id(.:format)        games#update
  #           DELETE /games/:id(.:format)        games#destroy
  resources :games

    #  Create route for end of game
    get 'games/:id/gameover' => 'games#gameover'

end

app/models/game.rb
class Game < ApplicationRecord
  has_many :puzzles
  belongs_to :user
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :check_if_logged_in, only: [:create]

  def new
    @game = Game.new
  end

  def create
    # User has requested a new game. Create a new game object and connect it to that user.
    # The newly created game is automatically the "in progress" game, and we also
    # initialise the score to zero.

    game  = Game.create user_id:@current_user.id, in_progress:true, score:0
     p game
     p game.errors
    # Make a request to the trivia API and retrieve 10 questions.
    # Save the questions from API as Puzzle items and associate them with the game.
    # Currently we are only utilising multiple choice by specifying that using the "type" param.
    trivia_api_url = "https://opentdb.com/api.php?amount=10&category=18&difficulty=easy&type=multiple"
    response = HTTParty.get trivia_api_url

    response["results"].each do |question_hash|
      # puts question_hash["question"]
      # puts question_hash["difficulty"]
      Puzzle.create(
        question: question_hash["question"],
        solution: question_hash["correct_answer"],
        incorrect_a: question_hash["incorrect_answers"][0],
        incorrect_b: question_hash["incorrect_answers"][1],
        incorrect_c: question_hash["incorrect_answers"][2],
        game_id: game.id
      )
    end
    # require "pry": binding.pry

    redirect_to game_path(game.id)

  end

  def index
    games = Game.all
    sortedgames = games.sort_by { |game| [game.score, game.updated_at] }.reverse
    @games = sortedgames.uniq(&:user_id)

  end

  def show
    @game = Game.find params[:id]
    @puzzle = Puzzle.where(game_id: params[:id])
  end

  def gameover
      @game = Game.find params[:id]
      @puzzle = Puzzle.where(game_id: params[:id])
  end

  def edit
    @game = Game.find params[:id]
  end

  def update
    game = Game.find params[:id]
    game.update game_params
  end

  def destroy
  end

  private
  def game_params
    params.require(:game).permit(:status, :user_id, :puzzle_id)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/gameover.html.erb
<article>
    <% if @current_user.present? %>
    <header class="centering">
        <%= image_tag 'TechCorpLogo.svg', alt: "Tech Job Corp", id: "game-logo" %>
    </header>
    <br/>
    <section>
        <header>
            <h1 class="page-title">
                Game over
            </h1>
        </header>

        <!-- Display offer letter to user with their 'salary' -->
        <div class="box-background">
        <p>
            Dear <strong><%= @game.user.username %></strong>,
        </p>
        <p>
            We are pleased to make you an offer of employment at Tech
            Job Corp. Your annual salary will be <strong>$ <%=@game.score %></strong>.
        </p>
        <p>
            Once you have signed your contract for eternal servitude, please collect your branded t-shirt, sticker and water bottle, and head to your assigned hotdesk. You now belong to us.
        </p>
        <p>
            Yours sincerly,
            <br />
            <%= link_to "Brooke", "https://github.com/dutchessoflx", :target => "_blank" %>,
            <%= link_to "Lucy", "https://github.com/LucySE/", :target => "_blank" %>,
            <%= link_to "Manda", "https://github.com/nimisaya", :target => "_blank" %>
            and
            <%= link_to "Reece", "https://github.com/reecen96", :target => "_blank" %>
            <br />
            <em>CEOs of Tech Job Corp.</em>
        </p>
        </div> <!-- class: box-background -->
    </section>
    <div class="spacer"></div>
    <section>
        <nav aria-label="Game menu" class="main-menu">
            <%=link_to 'Meet your top collegues', games_path, class: "button button-primary" %>
            <%= button_to 'Interview again for a pay rise', action: "create", class: "button button-secondary"  %>
        </nav>
    </section>
    <%end%>
</article>

app/views/games/index.html.erb
<h1>Leader Board of Hired Employees</h1>

<% @games.each do |g|%>
<span> Applicant Name:
<%= g.user.username%>
</span><br>
<span> Salary: $
<%= g.score %>
</span><br>
<span> Date Hired:
<%= g.updated_at %>
</span><br>
<span> Length of Interview:
<%= g.created_at - g.updated_at %>
</span><br>
<br/>
<% end %>


<% if @current_user.games.exists?%>
<%= button_to "Increase your Salary", action: "create" %>
<%= button_to "Or Review your Previous interviews", user_path(@current_user.id), class: "button button-secondary" %>
<% else %>
<%= button_to "Get Hired", action: "create" %>
<%end%>

app/views/games/new.html.erb
<h1>Welcome <%= @current_user.username %></h1>

<% if @current_user.present? %>
<section>
    <header>
        <h1 class="page-title">
            The Software Interview Game
        </h1>
    </header>
    <p>
        The late nights, exams, group projects (oh the humanity...), billions of resumes and it’s all come down to this...the interview!
        <br />
        <br />
        Well, we got you fam. Apply for the job at our 100% totally legit Tech Job Corp*. At Tech Job Corp we believe in ping pong tables, pointing at post-its, lines on whiteboards and slathering your laptop in stickers. Just submit your resume below and we’ll see you at your interview.
    </p>
</section>

<section>
    <nav aria-label="Game menu" class="main-menu">


    </nav>
</section>

<% end %>

<%= button_to "create new game", action: "create" %>
<%= link_to 'View our top employees', games_path, class: "button button-secondary" %><br>
<% if @current_user.games.exists?%>
<%= link_to 'View your Interview History', user_path(@current_user.id), class: "button button-secondary" %>
<%else%>
<%end%>

app/views/games/show.html.erb
<h1>Games#show</h1>

<div id= puzzle_chose>
<% p=@puzzle[3] %>
</div>

<ul>

<li> <%== p.question %> </li>
<li><input type=checkbox></input>
  <%== p.solution %> </li>
<li> <%== p.incorrect_a %> </li>
<li> <%== p.incorrect_b %> </li>
<li> <%== p.incorrect_c %> </li>
<br>
</div>

</ul>

<button type="button" id="next" >Back</button>
<button type="button" id="back">Next</button>
<br>
<br>

<%= javascript_pack_tag 'game' %>