config/routes.rb
Rails.application.routes.draw do

  # Root path
  root to: 'pages#home'


post '/users/:id' => 'users#show'
  # Create routes for users to create accounts, login and view/edit/delete their profile
  # users     GET    /users(.:format)          users#index
  #           POST   /users(.:format)          users#create
  # new_user  GET    /users/new(.:format)      users#new
  # edit_user GET    /users/:id/edit(.:format) users#edit
  # user      GET    /users/:id(.:format)      users#show
  #           PATCH  /users/:id(.:format)      users#update
  #           PUT    /users/:id(.:format)      users#update
  #           DELETE /users/:id(.:format)      users#destroy
  resources :users

  # Login/logout routes
  get '/login'  => 'session#new'        # showing the login form
  post '/login' => 'session#create'     # form submits to here, performs login, redirects
  delete '/login' => 'session#destroy'  # logout link goes here, perform logout, redirect

  # Create routes for puzzles - DO WE NEED ALL OF THESE ROUTES?
  #   puzzles GET    /puzzles(.:format)          puzzles#index
  #   POST   /puzzles(.:format)          puzzles#create
  # new_puzzle GET    /puzzles/new(.:format)      puzzles#new
  # edit_puzzle GET    /puzzles/:id/edit(.:format) puzzles#edit
  # puzzle GET    /puzzles/:id(.:format)      puzzles#show
  #   PATCH  /puzzles/:id(.:format)      puzzles#update
  #   PUT    /puzzles/:id(.:format)      puzzles#update
  #   DELETE /puzzles/:id(.:format)      puzzles#destroy
  resources :puzzles

  # Create routes for games - DO WE NEED ALL OF THESE ROUTES?
  #   games   GET    /games(.:format)            games#index
  #           POST   /games(.:format)            games#create
  # new_game  GET    /games/new(.:format)        games#new
  # edit_game GET    /games/:id/edit(.:format)   games#edit
  # game      GET    /games/:id(.:format)        games#show
  #           PATCH  /games/:id(.:format)        games#update
  #           PUT    /games/:id(.:format)        games#update
  #           DELETE /games/:id(.:format)        games#destroy
  resources :games

    #  Create route for end of game
    get 'games/:id/gameover' => 'games#gameover'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech Job Corp: The Game</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= favicon_link_tag asset_path('techcorp-favicon.svg') %>
  </head>

  <body>
  <div class="container">
    <header>
      <nav aria-label="Account menu">
        <ul>
        <% if @current_user.present? %>
          <li id="greeting-user">
            <%= @current_user.username %>
          </li>
          <!-- Temporary Nav for testing purposes only. -->
          <li>
            <%= link_to 'Puzzles', puzzles_path%>
          </li>
          <li>
            <%= link_to 'Games', games_path %>
          </li>
          <li>
            <%= link_to 'Logout', login_path, method: 'delete' %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Login', login_path %>
          </li>
          <li>
            <%= link_to 'Join', new_user_path  %>
          </li>
        <% end %>
        </ul>
      </nav>
      </header>
      <main>
        <%= yield %>
      </main>
      <footer>
        <small>&copy; <%= link_to "Brooke", "https://github.com/dutchessoflx", :target => "_blank" %>, <%= link_to "Lucy", "https://github.com/LucySE/", :target => "_blank" %>, <%= link_to "Manda", "https://github.com/nimisaya", :target => "_blank" %> and <%= link_to "Reece", "https://github.com/reecen96", :target => "_blank" %>, 2021</small>
      </footer>
    </div>
  </body>
</html>