config/routes.rb
Rails.application.routes.draw do

  # Root path
  root to: 'pages#home'


post '/users/:id' => 'users#show'
  # Create routes for users to create accounts, login and view/edit/delete their profile
  # users     GET    /users(.:format)          users#index
  #           POST   /users(.:format)          users#create
  # new_user  GET    /users/new(.:format)      users#new
  # edit_user GET    /users/:id/edit(.:format) users#edit
  # user      GET    /users/:id(.:format)      users#show
  #           PATCH  /users/:id(.:format)      users#update
  #           PUT    /users/:id(.:format)      users#update
  #           DELETE /users/:id(.:format)      users#destroy
  resources :users

  # Login/logout routes
  get '/login'  => 'session#new'        # showing the login form
  post '/login' => 'session#create'     # form submits to here, performs login, redirects
  delete '/login' => 'session#destroy'  # logout link goes here, perform logout, redirect

  # Create routes for puzzles - DO WE NEED ALL OF THESE ROUTES?
  #   puzzles GET    /puzzles(.:format)          puzzles#index
  #   POST   /puzzles(.:format)          puzzles#create
  # new_puzzle GET    /puzzles/new(.:format)      puzzles#new
  # edit_puzzle GET    /puzzles/:id/edit(.:format) puzzles#edit
  # puzzle GET    /puzzles/:id(.:format)      puzzles#show
  #   PATCH  /puzzles/:id(.:format)      puzzles#update
  #   PUT    /puzzles/:id(.:format)      puzzles#update
  #   DELETE /puzzles/:id(.:format)      puzzles#destroy
  resources :puzzles

  # Create routes for games - DO WE NEED ALL OF THESE ROUTES?
  #   games   GET    /games(.:format)            games#index
  #           POST   /games(.:format)            games#create
  # new_game  GET    /games/new(.:format)        games#new
  # edit_game GET    /games/:id/edit(.:format)   games#edit
  # game      GET    /games/:id(.:format)        games#show
  #           PATCH  /games/:id(.:format)        games#update
  #           PUT    /games/:id(.:format)        games#update
  #           DELETE /games/:id(.:format)        games#destroy
  resources :games

    #  Create route for end of game
    get 'games/:id/gameover' => 'games#gameover'

end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
  belongs_to :game
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  def new
    @puzzle = Puzzle.new
  end

  def create
    puzzle = Puzzle.create puzzle_params
    redirect_to puzzle_path

  end

  def index
    @puzzles = Puzzle.all
  end

  def show
    @puzzle = Puzzle.find params[:id]
    @puzzles = Puzzle.all

  end

  def edit
    @puzzle = Puzzle.find params[:id]
  end

  def update
    puzzle = Puzzle.find params[:id]
    puzzle.update puzzle_params
  end

  def destroy
  end

  private
  def puzzle_params
    params.require(:puzzle).permit(:question, :solution, :clue, :incorrect_a, :incorrect_a, :incorrect_c, :puzzle_type)
  end
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/views/puzzles/_form.html.erb
<%= form_with model:@puzzle, local:true, html: {multipart: true}  do |f| %>

<%= f.label :question %>
<%= f.text_field :question %>

<%= f.label :solution %>
<%= f.text_field :solution %>

<%= f.label :clue %>
<%= f.text_field :clue %>

<%= f.label :puzzle_type %>
<%= f.text_field :puzzle_type %>

<%= f.label :incorrect_a %>
<%= f.text_field :incorrect_a %>

<%= f.label :incorrect_b %>
<%= f.text_field :incorrect_b %>

<%= f.label :incorrect_c %>
<%= f.text_field :incorrect_c %>


<%= f.submit id:'submit_button'%>
<%end %>

app/views/puzzles/edit.html.erb
<h1>Puzzles#edit</h1>
<%= render partial: 'form' %>

app/views/puzzles/index.html.erb
<h1>Puzzles#index</h1>
<div >
  <% @puzzles.each do |p| %>
  <span>
    <%= link_to p.id, puzzle_path(p.id) %>
  </span> <br>
  <% end %>
  <div>
    <%= link_to "Add a Puzzle ", new_puzzle_path, class:"button"  %>
  </div>
</div>

app/views/puzzles/new.html.erb
<h1>Puzzles#new</h1>
<%= render partial: 'form' %>

app/views/puzzles/show.html.erb
<h1>Puzzles#show</h1>
<% if @puzzle.id === @puzzles.last.id %>
<p><%= @puzzle.question%></p>
<form action="/win" method="get">
  <label>
    <input type="radio" name="puzzle" value="<%=@current_user.scores.pluck(:puzzle_count).join().to_i+1%>">
    <%= @puzzle.solution%>
  </label>
  <label>
    <input type="radio" name="puzzle" value="0">
    <%= @puzzle.incorrect_a%>
  </label>
  <label>
    <input type="radio" name="puzzle" value="0">
    <%= @puzzle.incorrect_b%>
  </label>
  <label>
      <input type="radio" name="puzzle" value="0">
      <%= @puzzle.incorrect_c%>
    </label>
<input type="submit" value="Finish Quiz">
</form>
<% else %>
<p><%= @puzzle.question%></p>


<form action="/puzzles/<%=@puzzle.id+1%>" method="get">
  <label>
    <input type="radio" name="puzzle" value="<%=@current_user.scores.pluck(:puzzle_count).join().to_i+1%>">
    <%= @puzzle.solution%>
  </label>
  <label>
    <input type="radio" name="puzzle" value="<%=@current_user.scores.pluck(:puzzle_count).join().to_i%>">
    <%= @puzzle.incorrect_a%>
  </label>
  <label>
    <input type="radio" name="puzzle" value="<%=@puzzle.incorrect_b%>">
    <%= @puzzle.incorrect_b%>
  </label>
  <label>
      <input type="radio" name="puzzle" value="<%=@puzzle.incorrect_c%>">
      <%= @puzzle.incorrect_c%>
    </label>

  <input type="submit" value="Next Question">



</form>
<% end%>

<%= form_with model:@score, local:true, html: {multipart: true}  do |f| %>
<%= f.hidden_field :puzzle_count, value: @current_user.scores.pluck(:puzzle_count).join.to_i + params[:puzzle].to_i%>
<%= f.hidden_field :user_id, value: @current_user%>
<%= f.hidden_field :puzzle_id, value: @puzzle.id%>
<%= f.submit id:'submit_button'%>
<%end %>

<p>Current User: <%= @current_user.username %></p>
<p>Score= <%= @current_user.scores.pluck(:puzzle_count).join.to_i + params[:puzzle].to_i%></p>
<%= params %><br>
<%= params[:puzzle] %>